package com.test.model

import com.test.model.Message

global java.io.PrintStream out

rule "rule 1"
    no-loop true
    date-effective "2017-02-21 17:00:00"    //仅当当前日期和时间在日期有效属性后面时，才能激活规则。
    duration 2000
    when
        m : Message(name.equals("adeng") && age<5)
    then
        m.setAge(m.getAge()+1);
//        System.out.println(888);
//        out.println( m.getName() + ": " +  m.getText() );
        hello();
        System.out.println(m);
//        update(m);
end

function void hello(){
    System.out.println("test.hello");
}