package point;
//对一个规则文件而言，package是必须定义的，必须放在规则文件第一行。
//特别的是，package的名字是随意的，不必必须对应物理路径，跟java的package的概念不同，这里只是逻辑上的一种区分。
//同样的package下定义的function和query等可以直接使用。

import PointDomain;
//导入规则文件需要使用到的外部变量，这里的使用方法跟java相同，但是不同于java的是，这里的import导入的不仅仅可以是一个类，也可以是这个类中的某一个可访问的静态方法。

// 过生日，则加10分，并且将当月交易笔数翻倍后再计算积分
rule "birthdayPoint"
    salience 100    //优先级，数值越大越先执行，这个可以控制规则的执行顺序。
     // no-loop : 定义当前的规则是否不允许多次循环执行，默认是false
      // lock-on-active true：通过这个标签，可以控制当前的规则只会被执行一次
      // date-expires：设置规则的过期时间，默认的时间格式：“日-月-年” date-expires "2011-01-31 23:59:59"
      // date-effective：设置规则的生效时间，时间格式同上
      // duration：规则定时，duration 3000   3秒后执行规则
      //  salience：优先级，数值越大越先执行，这个可以控制规则的执行顺序

    lock-on-active true //通过这个标签，可以控制当前的规则只会被执行一次
    when
        $pointDomain:PointDomain(birthDay==true)
    then
        $pointDomain.setPoint($pointDomain.getPoint()+10);  //加10积分
        $pointDomain.setBuyNums($pointDomain.getBackNums()*2);
        $pointDomain.setBuyMoney($pointDomain.getBuyMoney()*2);
        $pointDomain.setBillThisMonth($pointDomain.getBillThisMonth()*2);       //以上三个翻倍

        $pointDomain.recordPointLog($pointDomain.getUserName(),"birthdayPoint");
end

//2011-01-08 - 2011-08-08每月信用卡还款3次以上，每满3笔赠送30分
rule "billThisMonthPoint"
    salience 99
    lock-on-active true
    date-effective "2011-01-08 23:59:59"     //设置规则的生效时间，时间格式同上
    date-expires "2011-08-08 23:59:59"       //设置规则的过期时间
    when
        $pointDomain:PointDomain(billThisMonth>=3)
    then
        $pointDomain.setPoint($pointDomain.getPoint()+$pointDomain.getBillThisMonth()/3*30);
        $pointDomain.recordPointLog($pointDomain.getUserName(),"billThisMonthPoint");
end

// 当月购物总金额100以上，每100元赠送10分
rule "buyMoneyPoint"
    salience 98
    lock-on-active true
    when
        pointDomain:PointDomain(buyMoney>=100)
    then
        pointDomain.setPoint(pointDomain.getPoint()+(int)pointDomain.getBuyMoney()/100*10);
        pointDomain.recordPointLog(pointDomain.getUserName(),"buyMoneyPoint");
end

//  当月购物次数5次以上，每五次赠送50分
rule "buyNumsPoint"
    salience 97
    lock-on-active true
    when
        $pointDomain:PointDomain(buyNums>=5)
    then
        $pointDomain.setPoint($pointDomain.getPoint()+$pointDomain.getBuyNums()/5*50);
        $pointDomain.recordPointLog($pointDomain.getUserName(),"buyNumsPoint");
end

// 特别的，如果全部满足了要求，则额奖励100积分
rule "allFitPoint"
    salience 96
    lock-on-active true
    when
        $pointDomain:PointDomain(buyNums>=5&& billThisMonth>=3 && buyMoney>=100)
    then
        $pointDomain.setPoint($pointDomain.getPoint()+100);
        $pointDomain.recordPointLog($pointDomain.getUserName(),"allFitPoint");
end